name: Run integration tests
on: [push]

jobs:
  run-integration-tests:
    name: Run integration tests
    runs-on: ubuntu-18.04

    steps:
      - name: Create Docker Images
        env:
            API_URL: ${{ secrets.API_URL }}
            MERCHANT_URL: ${{ secrets.MERCHANT_URL }}
            PARTNER_USERNAME: ${{ secrets.PARTNER_USERNAME }}
            PARTNER_PASSWORD: ${{ secrets.PARTNER_PASSWORD }}
            COMPANY_USERNAME: ${{ secrets.COMPANY_USERNAME }}
            COMPANY_PASSWORD: ${{ secrets.COMPANY_PASSWORD }}
        run: |
          wget https://github.com/IPPWorldwide/Docker/archive/refs/heads/main.zip
          unzip main.zip
          cd Docker-main
          docker-compose -f docker-compose.test.yml build
      - name: Start MerchantAdmin Containers
        run: |
          docker run -d --publish 9030:80 merchantadmin

      - name: Perform Integration Tests
        env:
            API_URL: ${{ secrets.API_URL }}
            MERCHANT_URL: ${{ secrets.MERCHANT_URL }}
            PARTNER_USERNAME: ${{ secrets.PARTNER_USERNAME }}
            PARTNER_PASSWORD: ${{ secrets.PARTNER_PASSWORD }}
            COMPANY_USERNAME: ${{ secrets.COMPANY_USERNAME }}
            COMPANY_PASSWORD: ${{ secrets.COMPANY_PASSWORD }}
        run: |
          docker run --env API_URL=${{ secrets.API_URL }} --env MERCHANT_URL=${{ secrets.MERCHANT_URL }} --env PARTNER_USERNAME=${{ secrets.PARTNER_USERNAME }} --env PARTNER_PASSWORD=${{ secrets.PARTNER_PASSWORD }} --env COMPANY_USERNAME=${{ secrets.COMPANY_USERNAME }} --env COMPANY_PASSWORD=${{ secrets.COMPANY_PASSWORD }} testcases ./vendor/bin/phpunit test

     
